import Navbar from "@/components/home/navbar/Navbar";
import "./globals.css";
import { Providers } from "./HeroProvider";
import Footer from "@/components/home/Footer";
export const metadata = {
  title: "News App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
        data-new-gr-c-s-check-loaded="14.1223.0"
        data-gr-ext-installed=""
        suppressHydrationWarning
      >
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
